#README.md has to be copied from root
site_name: dfm_tools documentation
use_directory_urls: false # true looks prettier but does not work locally
theme:
  name: material
  language: en
  # logo: images/HYDROLIB_logo_notext_mono_eroded.svg
  # custom_dir: docs/overrides
  features:
    # - navigation.instant
    # - navigation.tracking
    # - navigation.tabs #gives tab on top
    # - navigation.sections #gives non foldable toc
    - navigation.expand #expands toc in case of no sections
    # - navigation.top #not sure what this does
plugins:
  - search
  - mkdocs-jupyter: #https://github.com/danielfrg/mkdocs-jupyter
      include: ["*.py", "*.ipynb"]
      include_source: True
      execute: false # false is faster, but true gives you python script output in the docs. It requires `pip install -r requirements.txt` in the github action
      allow_errors: false
      execute_ignore:
        - "*.ipynb"
  # - autorefs
  # - table-reader
  # - macros:
     #  module_name: docs/include/mkdocs-macros/main
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: dfm_tools
          options:
            show_root_toc_entry: false
            show_source: true
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: true
            inherited_members: true
      watch:
        - dfm_tools
  - exclude:
      glob:
        - dfm_tools.pdf
        - dfm_tools.pptx
markdown_extensions:
  # - pymdownx.highlight
  # - pymdownx.superfence
  # - admonition
  - toc:
      permalink: true
repo_url: https://github.com/Deltares/dfm_tools
repo_name: deltares/dfm_tools
copyright: Copyright &copy; 2023 Deltares
# extra_css:
  # - stylesheets/extra.css

nav:
  - Home: "README.md"
  - How-to:
      - Installation: "installation.md"
      - Whats New: "whats-new.md"
      - Contributing: "CONTRIBUTING.md"
  - Tutorials:
      - Introduction: tutorials.md
      - notebooks/postprocessing_example.ipynb
      - notebooks/preprocessing_example_hydrolib.ipynb
      - notebooks/modelbuilder_example.ipynb
  - API reference:
      - API reference: api_reference.md #TODO: automate generation of this file
